export const GET_CATCH_FISH = 'GET_CATCH_FISH';


export const POST_CREATE_POST = 'POST_CREATE_POST';
export const POST_CREATE_POST_SUCCESS = 'POST_CREATE_POST_SUCCESS';
export const POST_CREATE_POST_FAIL = 'POST_CREATE_POST_FAIL';

export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';