export const GET_CATCH_FISH = 'GET_CATCH_FISH';


export const POST_CREATE_POST = 'POST_CREATE_POST';
export const POST_CREATE_POST_SUCCESS = 'POST_CREATE_POST_SUCCESS';
export const POST_CREATE_POST_FAIL = 'POST_CREATE_POST_FAIL';

export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';


export const GET_TOPIC = 'GET_TOPIC';
export const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS';
export const GET_TOPIC_FAIL = 'GET_TOPIC_FAIL';

export const POST_CREATE_TOPIC = 'POST_CREATE_TOPIC';
export const POST_CREATE_TOPIC_SUCCESS = 'POST_CREATE_TOPIC_SUCCESS';
export const POST_CREATE_TOPIC_FAIL = 'POST_CREATE_TOPIC_FAIL';

export const DELETE_TOPIC = 'DELETE_TOPIC';
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS';
export const DELETE_TOPIC_FAIL = 'DELETE_TOPIC_FAIL';